"""empty message

Revision ID: 0aa375b934cd
Revises: aea3e6312220
Create Date: 2021-05-16 10:02:48.986152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa375b934cd'
down_revision = 'aea3e6312220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'keyring', ['public_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'keyring', type_='unique')
    # ### end Alembic commands ###
