"""empty message

Revision ID: 469fa15fface
Revises: 
Create Date: 2021-05-11 07:21:28.553596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469fa15fface'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_version', sa.Integer(), nullable=False, default=1))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token_version')
    # ### end Alembic commands ###
