"""empty message

Revision ID: 85d5f438cfec
Revises: a26d5f109c84
Create Date: 2021-05-17 17:58:03.442514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d5f438cfec'
down_revision = 'a26d5f109c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_constraint('uq_chat_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_chat_name', ['name'])

    # ### end Alembic commands ###
