"""empty message

Revision ID: 86f11f2ecba3
Revises: 32dffc6f639c
Create Date: 2021-05-13 23:35:03.098582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f11f2ecba3'
down_revision = '32dffc6f639c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token_version')
    # ### end Alembic commands ###
