"""empty message

Revision ID: 97d221200bc9
Revises: 243c5c55bdce
Create Date: 2021-05-28 12:20:39.112340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d221200bc9'
down_revision = '243c5c55bdce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_dnt', sa.DateTime(), nullable=True))
        batch_op.drop_column('token_version')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_version', sa.INTEGER(), nullable=False))
        batch_op.drop_column('activity_dnt')

    # ### end Alembic commands ###
