"""empty message

Revision ID: ef986659abe7
Revises: 85d5f438cfec
Create Date: 2021-05-17 18:30:17.524420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef986659abe7'
down_revision = '85d5f438cfec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_chat_creator_id_user'), 'user', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chat_creator_id_user'), type_='foreignkey')
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
