"""empty message

Revision ID: fd832688fd28
Revises: ad8fcc56e8e6
Create Date: 2021-05-14 13:16:45.133654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd832688fd28'
down_revision = 'ad8fcc56e8e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'keyring', ['public_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'keyring', type_='unique')
    # ### end Alembic commands ###
